-- MySQL Script generated by MySQL Workbench
-- Sun Mar  9 11:34:26 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PF
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PF
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PF` DEFAULT CHARACTER SET utf8 ;
USE `PF` ;

-- -----------------------------------------------------
-- Table `PF`.`tb_instituicao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_instituicao` (
  `id_instituicao` INT NOT NULL AUTO_INCREMENT,
  `nome_instituicao` VARCHAR(100) NULL,
  `N.I.F.` INT NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  `endereço` VARCHAR(100) NULL,
  PRIMARY KEY (`id_instituicao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_aluno` (
  `B.I.N.` VARCHAR(20) NOT NULL,
  `nome_aluno` VARCHAR(100) NOT NULL,
  `data_de_nascimento` DATE NOT NULL,
  `sexo` ENUM('masculino', 'feminino') NOT NULL,
  `estado civil` ENUM('solteiro', 'casado') default 'solteiro' NOT NULL,
  `tb_instituicao_id_instituicao` INT NOT NULL,
  PRIMARY KEY (`B.I.N.`),
  INDEX `fk_tb_aluno_tb_instituicao_idx` (`tb_instituicao_id_instituicao` ASC),
  CONSTRAINT `fk_tb_aluno_tb_instituicao`
    FOREIGN KEY (`tb_instituicao_id_instituicao`)
    REFERENCES `PF`.`tb_instituicao` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_utilizador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_utilizador` (
  `id_utilizador` INT NOT NULL AUTO_INCREMENT,
  `nome_utilizador` VARCHAR(100) NOT NULL,
  `email_utilizador` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `data_criacao` TIMESTAMP DEFAULT current_timestamp ,
  `tipo` ENUM('admin','usuario') NOT NULL,
  PRIMARY KEY (`id_utilizador`),
  UNIQUE INDEX `email_UNIQUE` (`email_utilizador` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_salas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_salas` (
  `id_salas` INT NOT NULL AUTO_INCREMENT,
  `nome_sala` VARCHAR(45) NOT NULL,
  `capacidade` INT NOT NULL,
  PRIMARY KEY (`id_salas`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_ano_lectivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_ano_lectivo` (
  `id_ano_lectivo` INT NOT NULL AUTO_INCREMENT,
  `ano` VARCHAR(10) NOT NULL UNIQUE,
  `data_inicio` DATE NOT NULL,
  `data_fim` DATE NOT NULL,
  PRIMARY KEY (`id_ano_lectivo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `nome_turma` VARCHAR(50) NOT NULL,
  `tb_salas_id_salas` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_tb_turma_tb_salas1_idx` (`tb_salas_id_salas` ASC),
  CONSTRAINT `fk_tb_turma_tb_salas1`
    FOREIGN KEY (`tb_salas_id_salas`)
    REFERENCES `PF`.`tb_salas` (`id_salas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_mensalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_mensalidade` (
  `id_mensalidade` INT NOT NULL,
  `valor_mensalidade` DECIMAL(10,2) NOT NULL,
  `curso` VARCHAR(50) NOT NULL,
  `tb_instituicao_id_instituicao` INT NOT NULL,
  `multa` DECIMAL(10,2) NOT NULL default (0.00),
  PRIMARY KEY (`id_mensalidade`),
  INDEX `fk_tb_mensalidade_tb_instituicao1_idx` (`tb_instituicao_id_instituicao` ASC),
  CONSTRAINT `fk_tb_mensalidade_tb_instituicao1`
    FOREIGN KEY (`tb_instituicao_id_instituicao`)
    REFERENCES `PF`.`tb_instituicao` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nome_curso` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `tb_mensalidade_id_mensalidade` INT NOT NULL,
  `tb_turma_id_turma` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_tb_cursos_tb_mensalidade1_idx` (`tb_mensalidade_id_mensalidade` ASC),
  INDEX `fk_tb_cursos_tb_turma1_idx` (`tb_turma_id_turma` ASC),
  CONSTRAINT `fk_tb_cursos_tb_mensalidade1`
    FOREIGN KEY (`tb_mensalidade_id_mensalidade`)
    REFERENCES `PF`.`tb_mensalidade` (`id_mensalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_cursos_tb_turma1`
    FOREIGN KEY (`tb_turma_id_turma`)
    REFERENCES `PF`.`tb_turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_enquadramento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_enquadramento` (
  `id_enquadramento` INT NOT NULL,
  `tipo` ENUM('normal','bolsa','desconto') default 'normal',
  `tb_cursos_id_curso` INT NOT NULL,
  `tb_aluno_B.I.N.` VARCHAR(20) NOT NULL,
  `tb_ano_lectivo_id_ano_lectivo` INT NOT NULL,
  `tb_utilizador_id_utilizador` INT NOT NULL,
  `tb_instituicao_id_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_enquadramento`),
  INDEX `fk_tb_enquadramento_tb_cursos1_idx` (`tb_cursos_id_curso` ASC),
  INDEX `fk_tb_enquadramento_tb_aluno1_idx` (`tb_aluno_B.I.N.` ASC),
  INDEX `fk_tb_enquadramento_tb_ano_lectivo1_idx` (`tb_ano_lectivo_id_ano_lectivo` ASC),
  INDEX `fk_tb_enquadramento_tb_utilizador1_idx` (`tb_utilizador_id_utilizador` ASC),
  INDEX `fk_tb_enquadramento_tb_instituicao1_idx` (`tb_instituicao_id_instituicao` ASC),
  CONSTRAINT `fk_tb_enquadramento_tb_cursos1`
    FOREIGN KEY (`tb_cursos_id_curso`)
    REFERENCES `PF`.`tb_cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enquadramento_tb_aluno1`
    FOREIGN KEY (`tb_aluno_B.I.N.`)
    REFERENCES `PF`.`tb_aluno` (`B.I.N.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enquadramento_tb_ano_lectivo1`
    FOREIGN KEY (`tb_ano_lectivo_id_ano_lectivo`)
    REFERENCES `PF`.`tb_ano_lectivo` (`id_ano_lectivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enquadramento_tb_utilizador1`
    FOREIGN KEY (`tb_utilizador_id_utilizador`)
    REFERENCES `PF`.`tb_utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_enquadramento_tb_instituicao1`
    FOREIGN KEY (`tb_instituicao_id_instituicao`)
    REFERENCES `PF`.`tb_instituicao` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_pagamento` (
  `id_pagamento` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `data_pagameno` DATE NOT NULL,
  `metodo_pagamento` ENUM('cartão','transferência','dinheiro') NOT NULL,
  `status` ENUM('pendente','pago','atrasado') default 'pendente',
  `tb_mensalidade_id_mensalidade` INT NOT NULL,
  `tb_aluno_B.I.N.` VARCHAR(20) NOT NULL,
  `tb_utilizador_id_utilizador` INT NOT NULL,
  `multa` ENUM('sim','nao') default 'nao',
  PRIMARY KEY (`id_pagamento`),
  INDEX `fk_tb_pagamento_tb_mensalidade1_idx` (`tb_mensalidade_id_mensalidade` ASC),
  INDEX `fk_tb_pagamento_tb_aluno1_idx` (`tb_aluno_B.I.N.` ASC),
  INDEX `fk_tb_pagamento_tb_utilizador1_idx` (`tb_utilizador_id_utilizador` ASC),
  CONSTRAINT `fk_tb_pagamento_tb_mensalidade1`
    FOREIGN KEY (`tb_mensalidade_id_mensalidade`)
    REFERENCES `PF`.`tb_mensalidade` (`id_mensalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pagamento_tb_aluno1`
    FOREIGN KEY (`tb_aluno_B.I.N.`)
    REFERENCES `PF`.`tb_aluno` (`B.I.N.`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_pagamento_tb_utilizador1`
    FOREIGN KEY (`tb_utilizador_id_utilizador`)
    REFERENCES `PF`.`tb_utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_estorno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_estorno` (
  `id_estorno` INT NOT NULL AUTO_INCREMENT,
  `valor` DECIMAL(10,2) NOT NULL,
  `motivo` text NOT NULL,
  `data_estorno` DATE NOT NULL,
  `tb_pagamento_id_pagamento` INT NOT NULL,
  `tb_utilizador_id_utilizador` INT NOT NULL,
  `tb_instituicao_id_instituicao` INT NOT NULL,
  PRIMARY KEY (`id_estorno`),
  INDEX `fk_tb_estorno_tb_pagamento1_idx` (`tb_pagamento_id_pagamento` ASC),
  INDEX `fk_tb_estorno_tb_utilizador1_idx` (`tb_utilizador_id_utilizador` ASC),
  INDEX `fk_tb_estorno_tb_instituicao1_idx` (`tb_instituicao_id_instituicao` ASC),
  CONSTRAINT `fk_tb_estorno_tb_pagamento1`
    FOREIGN KEY (`tb_pagamento_id_pagamento`)
    REFERENCES `PF`.`tb_pagamento` (`id_pagamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_estorno_tb_utilizador1`
    FOREIGN KEY (`tb_utilizador_id_utilizador`)
    REFERENCES `PF`.`tb_utilizador` (`id_utilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_estorno_tb_instituicao1`
    FOREIGN KEY (`tb_instituicao_id_instituicao`)
    REFERENCES `PF`.`tb_instituicao` (`id_instituicao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PF`.`tb_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PF`.`tb_documento` (
  `id_documento` INT NOT NULL,
  `nome_documento` VARCHAR(100) NULL,
  `descricao` VARCHAR(255) NULL,
  PRIMARY KEY (`id_documento`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
show databases;